### ISSUE TITLE
Upgrade flutter_map version

### ISSUE THREAD

**Issue by Friendly-Banana** [androidseb/flutter_map_floating_marker_titles#8]
Hello,
flutter_map's latest version is 3.0.0.
Could you please update your library to support it?
Thanks

**Comment by Friendly-Banana** [comment]
@androidseb can you please look into this?

**Comment by androidseb** [comment]
Hey, yes this is on my list, I will look at that when I have some time, probably in the next week or so.

The changes of version 3 are interesting, there are important breaking changes so I'll take some time to look at this thoroughly, I'm thinking introducing the floating titles as a layer rather than keeping the map container I've been using up until now.

**Comment by Friendly-Banana** [comment]
That's great news.

**Comment by gri38** [comment]
Hi. Thanks a lot for your plugin ! I'm also using it for my app.
Can you give some visibility about you update to flutter_map V3 ? 1 week, 1 month ...?

Please, don't misinterpret my words: I just ask for visibility, not pressure.

**Comment by androidseb** [comment]
Hey, thanks for asking, I have to say it's the first time I have two people waiting at the same time, I'm glad my lib is useful to you :-)

I have been busy with the rewrite of my app lately and pushing this back. I will need this upgrade as well eventually, so I'll try to get this done soon.

I would feel confident saying before end of November almost for sure. Probably by mid-November, just another week I think.

**Comment by gri38** [comment]
Hi @androidseb 
Thanks you very much for your answer.
I'll can be a tester of your new vesrsion ! I'll let you know.

**Comment by androidseb** [comment]
Alright, this is now [done](https://pub.dev/packages/flutter_map_floating_marker_titles) with version `0.4.0`.
Enjoy!

I [tried](https://github.com/androidseb/flutter_map_floating_marker_titles/commit/cd46a054b92ed473a1b71632059f24164c83a0c0) to make the floating marker titles available as a child layer, but the result was not conclusive, state management is tricky.

I might do that later, but for now the library will remain like this.

Since the library is now updated to support flutter_map 3.0.0, I'll close this issue now, please re-open if I missed something, thanks!

**Comment by Friendly-Banana** [comment]
Perfect, thanks a lot.

**Comment by gri38** [comment]
Hi.
Thank you SOOOOO MUCH.
I've spent some time to use your new version of the lib, it works like a charm !
