### ISSUE TITLE
Offset of the markers?

### ISSUE THREAD

**Issue by Mr-Jeeva** [androidseb/flutter_map_floating_marker_titles#9]
can we get screen offset of the markers?

**Comment by androidseb** [comment]
Hello, I'm not sure what you're asking for, this library allows you to display floating markers on a map, what do you mean by "getting the screen offset of the markers"? Do you mean some sort of listener firing off the marker's coordinates when visible on screen?

**Comment by yakou32** [comment]
I suppose @Mr-Jeeva meant a visual offset.

Indeed, I have a similar question, using floating titles in conjunction with graphic marker:
![image](https://github.com/user-attachments/assets/dce92977-e3f6-47d2-9b64-1430da83c5c9)

It would be nice to be able to customize an offset (e.g. bottom 40, left 40) so that the text nicely fits with a graphical marker.

**Comment by androidseb** [comment]
@yakou32 isn't that already possible with the view-wide customization options described [here](https://github.com/androidseb/flutter_map_floating_marker_titles?tab=readme-ov-file#view-wide-customization-options)? Something like this?

```
FMTOOptions(
  //...
  titlePlacementPolicy: const FloatingMarkerPlacementPolicy(FloatingMarkerGravity.left, 40),
  //...
),
```

Or do you mean something else?
